openapi: 3.1.0
info:
  title: Robot rollout verifier Archive Opus API
  version: 0.1.0
tags:
- name: Opus
paths:
  /api/opus:
    post:
      summary: Opus Endpoint
      operationId: opus_endpoint_api_opus_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpusReq'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Opus
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    OpusReq:
      properties:
        task:
          type: string
          title: Task
        clip_id:
          type: string
          title: Clip Id
        name:
          anyOf:
          - type: string
          - type: 'null'
          title: Name
      type: object
      required:
      - task
      - clip_id
      title: OpusReq
